services:
  transactionprocessor:
    container_name: transactionprocessor
    build:
      context: .
      dockerfile: PagueVeloz.TransactionProcessor/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    user: "0:0"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development

      # SUA CHAVE: DefaultConnection
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=transaction_processor;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False"

      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: "5672"
      RabbitMQ__User: ${RABBITMQ_DEFAULT_USER}
      RabbitMQ__Pass: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - pvnet

  sqlserver:
    container_name: pv-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - pvnet

  rabbitmq:
    container_name: pv-rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - pvnet

networks:
  pvnet:

volumes:
  sqlserver_data:
  rabbitmq_data:
